### ISSUE TITLE
Xcode show an error that "method unavailable in tvOS" on the Swift Package Manager.

### ISSUE THREAD

**Issue by RomanS001** [BeauNouvelle/SimpleCheckbox#35]
<img width="1290" alt="Снимок экрана 2021-07-31 в 22 29 33" src="https://user-images.githubusercontent.com/68818066/127750611-89db7b97-d000-4b76-9992-cb957f4b521b.png">

**Comment by BeauNouvelle** [comment]
Hello, thanks for reporting this. 

I suggest that you remove this package from your tvOS target to avoid this issue.

I don't think this control would work well on tvOS anyway, since it can't be focused (please let me know if I'm wrong, as I haven't tested)

In saying that though, this checkbox COULD be useful on tvOS for display purposes only, providing you don't expect any user interaction. So I'll get this fixed up
